### ISSUE TITLE
interrupt priority

### ISSUE THREAD

**Issue by antimodular** [jimparis/DmxReceiver#3]
hi.

i have been using your library for a while now. it's great. a big thanks to you.

i am now using it in conjunction with an attachInterrupt to catch the zero crossing of an AC signal. that works fine too, but sometimes that interrupt does not get caught, and i am guessing because the dmx usart interrupt has a higher priority.

do you know how to lower the DMX library's interrupt priority?

do you think converting the DMX library to use DMA channels would be a good idea?

thanks, stephan.

**Comment by jimparis** [comment]
I don't think DMA is the answer.  The lower-level UART receive routines can (and may) already use DMA for reception of the normal bytes; I don't recall what's in the Teensy driver code.  And the frame detection can't really use it because of how we're (mis-)using the UART peripheral's BREAK detection.

Interrupt priority, and the fact that `DmxReceiver::bufferService` and `DmxReceiver::fill` temporarily disable interrupts, definitely should **not** cause other interrupts to get lost.  If an external pin interrupt flag gets set, it will still interrupt a bit later once the higher-priority interrupt completes.

There may be some issue with calling `__disable_irq()` and `__enable_irq()` from within `uart0_error_isr` (through `::bufferService`), but I think that's safe to do on Cortex-M.  You could try changing that (just make `uart0_error_isr` call a new version of that function that omits those calls) but I don't expect it to have any effect.

If you do want to try reducing the DMX error interrupt priority, set it to something like:

```
NVIC_SET_PRIORITY(IRQ_UART0_ERROR, 240);
```

after calling DmxReceiver::begin()

**Comment by antimodular** [comment]
thanks. i will give it a try and report back.
